GET http://localhost:0418/hello
Accept: application/json

###

POST http://localhost:0418/hello/post
Content-Type: application/x-www-form-urlencoded

name=Eason

###

GET http://localhost:0418/test/list
